// ionic-client/src/app/chart/filters/chart-filters.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import * as moment from 'moment';
import { SERIES } from './constants';

const mapNurseToDateOption = ({ date }) => ({
  value: date,
  label: moment(date).format('MMMM Do'),
});

@Component({
  selector: 'chart-filters',
  templateUrl: './chart-filters.component.html',
  styleUrls: ['./chart-filters.component.scss']
})
export class ChartFilters {
  public options = [];
  public series = Object.keys(SERIES).map(key => ({ key, label: SERIES[key] }));

  @Input() startDate;
  @Input() selectedSeries;
  @Output() selectDate: EventEmitter<Date>;
  @Output() selectSeries: EventEmitter<string>;

  constructor() {
    this.selectDate = new EventEmitter<Date>();
    this.selectSeries = new EventEmitter<string>();
  }

  @Input()
  set nursingRecords(nursingRecords) {
    this.options = (nursingRecords || []).map(mapNurseToDateOption);
  }

  onChange(event) {
    const date = event.detail.value;

    if (date !== this.startDate) {
      this.selectDate.emit(date);
    }
  }

  onSelectSeries(series) {
    if (series !== this.selectedSeries) {
      this.selectSeries.emit(series);
    }
  }
}

<div id="chart-filters-container" class="ba bw2 ph4 pt0 pb3">
  <h2>Graph Options</h2>
  <ion-label>Start date</ion-label>
  <ion-select
    class="ba br2 mv2 pr2 pl2"
    placeholder="Select a date"
    [value]="startDate"
    (ionChange)="onChange($event)">
    <ion-select-option *ngFor="let date of options" [value]="date.value">
      {{date.label}}
    </ion-select-option>
  </ion-select>
  <ion-label>Type</ion-label>
  <div class="btn-group flex mt2">
    <button
      *ngFor="let type of series"
      (click)="onSelectSeries(type.label)"
      class="{{selectedSeries === type.label ? 'selected' : ''}}">
      {{type.label}}
    </button>
  </div>
</div>

// react-client/src/components/OzFedChart/ChartFilters.js
import moment from 'moment';
import React from 'react';
import Select from 'react-select';
import { Button, Colors } from '../library';

export const SERIES = {
  PRODUCED: 'Produced',
  CONSUMED: 'Consumed',
};

const SeriesSelect = ({ series, setSeries, style }) => (
  <div style={style}>
    Type
    <div className="btn-group flex mt2">
      {Object.keys(SERIES).map((key) => (
        <Button
          key={key}
          style={{ flexGrow: 1 }}
          onClick={() => setSeries(SERIES[key])}
          selected={series === SERIES[key]}>
          {SERIES[key]}
        </Button>
      ))}
    </div>
  </div>
);

const mapNurseToDateOption = ({ date }) => ({
  value: date,
  label: moment(date).format('MMMM Do'),
});

const withDateOptions = (WrappedComponent) => (
  class MapNursingRecordsToOptions extends React.Component {
    constructor(props) {
      super(props);

      this.state = { options: [] };
    }

    componentDidUpdate(prevProps) {
      const { nursingRecords } = this.props;
      const { options } = this.state;

      if (nursingRecords.length > options.length) {
        this.setState({ options: nursingRecords.map(mapNurseToDateOption) });
      }
    }

    render = () => (
      <WrappedComponent {...this.props} options={this.state.options} />
    )
  }
)


const SelectStartDate = withDateOptions(({ options, startDate, setStartDate, className, style }) => (
  <div className={className} style={style}>
    Start date
    <div className="mt2">
      <Select value={startDate} onChange={setStartDate} options={options} />
    </div>
  </div>
));

const ChartFilter = (props) => (
  <div
    className="ba bw2 ph4 pt0 pb3 ml5"
    style={{
      flex: '1 1 0',
      borderColor: Colors.Grey.Lightest,
      backgroundColor: Colors.Grey.White,
    }}>
    <h2>Graph Options</h2>
    <SeriesSelect {...props} style={{ flexGrow: 1 }} />
    <SelectStartDate {...props} className="mt3" />
  </div>
);

export default ChartFilter;
